/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillPayment {
  'status' : TransactionStatus,
  'date' : Time,
  'billType' : BillType,
  'amount' : bigint,
}
export type BillType = { 'electricity' : null } |
  { 'mobile' : null } |
  { 'water' : null };
export interface Merchant { 'name' : string, 'merchantId' : Principal }
export type Time = bigint;
export interface Transaction {
  'status' : TransactionStatus,
  'date' : Time,
  'merchant' : Merchant,
  'amount' : bigint,
}
export type TransactionStatus = { 'successful' : null } |
  { 'failed' : null };
export interface _SERVICE {
  'addMoney' : ActorMethod<[bigint], undefined>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBillPayments' : ActorMethod<[], Array<BillPayment>>,
  'getMonthlySpent' : ActorMethod<[], bigint>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'makePayment' : ActorMethod<[Principal, string, bigint], undefined>,
  'payBill' : ActorMethod<[BillType, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];