/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionStatus = IDL.Variant({
  'successful' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Merchant = IDL.Record({
  'name' : IDL.Text,
  'merchantId' : IDL.Principal,
});
export const Transaction = IDL.Record({
  'status' : TransactionStatus,
  'date' : Time,
  'merchant' : Merchant,
  'amount' : IDL.Nat,
});
export const BillType = IDL.Variant({
  'electricity' : IDL.Null,
  'mobile' : IDL.Null,
  'water' : IDL.Null,
});
export const BillPayment = IDL.Record({
  'status' : TransactionStatus,
  'date' : Time,
  'billType' : BillType,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMoney' : IDL.Func([IDL.Nat], [], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBillPayments' : IDL.Func([], [IDL.Vec(BillPayment)], ['query']),
  'getMonthlySpent' : IDL.Func([], [IDL.Nat], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'makePayment' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
  'payBill' : IDL.Func([BillType, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionStatus = IDL.Variant({
    'successful' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Merchant = IDL.Record({
    'name' : IDL.Text,
    'merchantId' : IDL.Principal,
  });
  const Transaction = IDL.Record({
    'status' : TransactionStatus,
    'date' : Time,
    'merchant' : Merchant,
    'amount' : IDL.Nat,
  });
  const BillType = IDL.Variant({
    'electricity' : IDL.Null,
    'mobile' : IDL.Null,
    'water' : IDL.Null,
  });
  const BillPayment = IDL.Record({
    'status' : TransactionStatus,
    'date' : Time,
    'billType' : BillType,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMoney' : IDL.Func([IDL.Nat], [], []),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBillPayments' : IDL.Func([], [IDL.Vec(BillPayment)], ['query']),
    'getMonthlySpent' : IDL.Func([], [IDL.Nat], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'makePayment' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
    'payBill' : IDL.Func([BillType, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };