/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillPayment {
    status: TransactionStatus;
    date: Time;
    billType: BillType;
    amount: bigint;
}
export type Time = bigint;
export interface Merchant {
    name: string;
    merchantId: Principal;
}
export interface Transaction {
    status: TransactionStatus;
    date: Time;
    merchant: Merchant;
    amount: bigint;
}
export enum BillType {
    electricity = "electricity",
    mobile = "mobile",
    water = "water"
}
export enum TransactionStatus {
    successful = "successful",
    failed = "failed"
}
export interface backendInterface {
    addMoney(amount: bigint): Promise<void>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getBillPayments(): Promise<Array<BillPayment>>;
    getMonthlySpent(): Promise<bigint>;
    getWalletBalance(): Promise<bigint>;
    makePayment(merchantId: Principal, merchantName: string, amount: bigint): Promise<void>;
    payBill(billType: BillType, amount: bigint): Promise<void>;
}
import type { BillPayment as _BillPayment, BillType as _BillType, Merchant as _Merchant, Time as _Time, Transaction as _Transaction, TransactionStatus as _TransactionStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMoney(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoney(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoney(arg0);
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillPayments(): Promise<Array<BillPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillPayments();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillPayments();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlySpent(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySpent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySpent();
            return result;
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async makePayment(arg0: Principal, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makePayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makePayment(arg0, arg1, arg2);
            return result;
        }
    }
    async payBill(arg0: BillType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.payBill(to_candid_BillType_n11(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payBill(to_candid_BillType_n11(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_BillPayment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillPayment): BillPayment {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BillType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillType): BillType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransactionStatus;
    date: _Time;
    merchant: _Merchant;
    amount: bigint;
}): {
    status: TransactionStatus;
    date: Time;
    merchant: Merchant;
    amount: bigint;
} {
    return {
        status: from_candid_TransactionStatus_n4(_uploadFile, _downloadFile, value.status),
        date: value.date,
        merchant: value.merchant,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransactionStatus;
    date: _Time;
    billType: _BillType;
    amount: bigint;
}): {
    status: TransactionStatus;
    date: Time;
    billType: BillType;
    amount: bigint;
} {
    return {
        status: from_candid_TransactionStatus_n4(_uploadFile, _downloadFile, value.status),
        date: value.date,
        billType: from_candid_BillType_n9(_uploadFile, _downloadFile, value.billType),
        amount: value.amount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    electricity: null;
} | {
    mobile: null;
} | {
    water: null;
}): BillType {
    return "electricity" in value ? BillType.electricity : "mobile" in value ? BillType.mobile : "water" in value ? BillType.water : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    successful: null;
} | {
    failed: null;
}): TransactionStatus {
    return "successful" in value ? TransactionStatus.successful : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillPayment>): Array<BillPayment> {
    return value.map((x)=>from_candid_BillPayment_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BillType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillType): _BillType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillType): {
    electricity: null;
} | {
    mobile: null;
} | {
    water: null;
} {
    return value == BillType.electricity ? {
        electricity: null
    } : value == BillType.mobile ? {
        mobile: null
    } : value == BillType.water ? {
        water: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
